### PR TITLE
Feature/35 dependency modeler errors and warnings

### LINKED ISSUE #52: Dependency Modeler includes errors & warnings
## User stories
As a user I want to be notified throughout errors and warning while working in the dependency modeler in order to have a correct and useful diagram.

## Dependencies
Depends on: 
 - #40 
 - #45 

## Acceptance Criteria
- [x] A warning gets displayed when the user creates an objective that isn't linked to any other one
- [x] An error gets displayed when the user links all objectives in a circle // when the Start State gets excluded by the sequence

### PR DESCRIPTION
**Pull request by lottebalcke**
Fixes #52 

Implements warnings and errors in the dependency modeler

## PR checklist

- [x] dev-branch has been merged into local branch to resolve conflicts
- [x] the application has been manually tested after merge
- [x] another dev reviewed and approved
- [x] if feature-Branch: Teams PO has approved (show via e.g. screenshots/screencapture/live demo)

### CODE REVIEW

**Review by simonmichaelnowack — CHANGES_REQUESTED** [review]
missing warning when there are 2 graphs

**Comment by lottebalcke** [comment]
I added an error for creating a cycle. Please review again!

**Review by Franka-T — APPROVED** [review]
looks good :)

**Review by simonmichaelnowack — CHANGES_REQUESTED** [review]
image
I think there is still no warning :(

**Comment by Firsttryy** [comment]
Ich denke das von Simon angesprochene Problem löst sich ja dann, wenn wir nur eine einzige Sequenz erlauben?

**Comment by lottebalcke** [comment]
@simonmichaelnowack Doesn't happen for me...(see screenshot)
Did you work on the most recent version?

Screenshot 2023-03-23 at 21 44 18

**Comment by lottebalcke** [comment]
@Noel-Bastubbe Ich meine das Problem eigentlich gelöst zu haben...

**Review by simonmichaelnowack — APPROVED** [review]
Awesome! Great work

**Pull request merged**
